<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="2359id-MacAir.local" failures="1" tests="5" name="Regresion test for 1.5.35" time="40.945" errors="0" timestamp="19 Jun 2019 07:14:21 GMT">
  <testcase classname="TestCases.AuthenticationUserSignIn" name="A_001_AuthenticationWithUnregisteredCompanyUser" time="3.142"/>
  <testcase classname="TestCases.AuthenticationUserSignIn" name="A_002_AuthenticationWithUnregisteredUserName" time="2.623"/>
  <testcase classname="TestCases.AuthenticationUserSignIn" name="A_003_AuthenticationWithInvalidPassword" time="2.612"/>
  <testcase classname="TestCases.AuthenticationUserSignIn" name="A_005_AuthenticationWithEmptyUserName" time="2.488"/>
  <testcase classname="TestCases.AuthenticationUserSignIn" name="A_006_AuthenticationWithEmptyPassword" time="2.498">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestCases.AuthenticationUserSignIn.A_006_AuthenticationWithEmptyPassword(AuthenticationUserSignIn.java:236)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- A_006_AuthenticationWithEmptyPassword -->
  <testcase classname="TestCases.AuthenticationUserSignIn" name="A_004_AuthenticationWithEmptyCompanyUserName" time="0.0">
    <ignored/>
  </testcase> <!-- A_004_AuthenticationWithEmptyCompanyUserName -->
</testsuite> <!-- Regresion test for 1.5.35 -->
